In [1]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [2]:
type(L[0])

int

In [3]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [4]:
type(L2[0])

str

In [5]:
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [6]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
import numpy as np

In [8]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [9]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [10]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [11]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

In [12]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
np.random.random((3, 3))

array([[0.27250198, 0.15036421, 0.63803766],
       [0.05838856, 0.85828364, 0.78755882],
       [0.56505903, 0.1582295 , 0.81079464]])

In [18]:
np.random.normal(0, 1, (3, 3))

array([[ 1.43806570e+00,  1.66298278e+00, -2.44292815e+00],
       [-6.49161931e-02, -8.61010019e-02, -3.16169021e-04],
       [-5.36392809e-01, -1.09976654e+00, -1.64333348e-01]])

In [19]:
np.random.randint(0, 10, (3, 3))

array([[0, 7, 8],
       [9, 0, 8],
       [5, 8, 3]])

In [20]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [21]:
np.empty(3)

array([1., 1., 1.])

In [22]:
import numpy as np
rng = np.random.default_rng(seed=1701) 

x1 = rng.integers(10, size=6) 
x2 = rng.integers(10, size=(3, 4)) 
x3 = rng.integers(10, size=(3, 4, 5)) 

In [23]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)
print("dtype:   ", x3.dtype)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60
dtype:    int64


In [24]:
x1

array([9, 4, 0, 3, 8, 6], dtype=int64)

In [25]:
x1[0]

9

In [26]:
x1[4]

8

In [27]:
x1[-1]

6

In [28]:
x1[-2]

8

In [29]:
x2

array([[3, 1, 3, 7],
       [4, 0, 2, 3],
       [0, 0, 6, 9]], dtype=int64)

In [30]:
x2[0, 0]

3

In [31]:
x2[2, 0]

0

In [32]:
x2[2, -1]

9

In [33]:
x2[0, 0] = 12
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [34]:
x1[0] = 3.14159 
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [35]:
x1

array([3, 4, 0, 3, 8, 6], dtype=int64)

In [36]:
x1[:3] 

array([3, 4, 0], dtype=int64)

In [37]:
x1[3:] 

array([3, 8, 6], dtype=int64)

In [38]:
x1[1:4]  

array([4, 0, 3], dtype=int64)

In [39]:
x1[::2]

array([3, 0, 8], dtype=int64)

In [40]:
x1[1::2]

array([4, 3, 6], dtype=int64)

In [41]:
x1[::-1]

array([6, 8, 3, 0, 4, 3], dtype=int64)

In [42]:
x1[4::-2] 

array([8, 0, 3], dtype=int64)

In [43]:
x2

array([[12,  1,  3,  7],
       [ 4,  0,  2,  3],
       [ 0,  0,  6,  9]], dtype=int64)

In [44]:
x2[:2, :3] 

array([[12,  1,  3],
       [ 4,  0,  2]], dtype=int64)

In [45]:
x2[:3, ::2] 

array([[12,  3],
       [ 4,  2],
       [ 0,  6]], dtype=int64)

In [46]:
x2[::-1, ::-1]

array([[ 9,  6,  0,  0],
       [ 3,  2,  0,  4],
       [ 7,  3,  1, 12]], dtype=int64)

In [47]:
x2[:, 0] 

array([12,  4,  0], dtype=int64)

In [48]:
x2[0, :] 

array([12,  1,  3,  7], dtype=int64)

In [49]:
x2[0] 

array([12,  1,  3,  7], dtype=int64)

In [50]:
print(x2)

[[12  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [51]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  1]
 [ 4  0]]


In [52]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  1]
 [ 4  0]]


In [53]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [54]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  1]
 [ 4  0]]


In [55]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  1]
 [ 4  0]]


In [56]:
print(x2)

[[99  1  3  7]
 [ 4  0  2  3]
 [ 0  0  6  9]]


In [57]:
grid = np.arange(1, 10).reshape(3, 3)
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [58]:
x = np.array([1, 2, 3])
x.reshape((1, 3)) 

array([[1, 2, 3]])

In [59]:
x.reshape((3, 1)) 

array([[1],
       [2],
       [3]])

In [60]:
x[np.newaxis, :] 

array([[1, 2, 3]])

In [61]:
x[:, np.newaxis] 

array([[1],
       [2],
       [3]])

In [62]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [63]:
z = np.array([99, 99, 99])
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [64]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [65]:
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [66]:
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [67]:
np.vstack([x, grid])

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [68]:
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 1,  2,  3, 99],
       [ 4,  5,  6, 99]])

In [69]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [70]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [71]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [72]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
